In [2]:
# coding=utf-8
import numpy as np

In [5]:
a_list = list(range(10))
b=np.array(a_list)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
z = np.zeros(10)
z.dtype

dtype('float64')

In [14]:
z = np.zeros((5,5), dtype=int)
z

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [15]:
f=np.full((3,4),3.14)
f.dtype

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])